### PR TITLE
Resolve #77

### LINKED ISSUE #77: Strange Error
I am getting the following error:

`/dev/fd/63: line 1: 400:: command not found`

### PR DESCRIPTION
**Pull request by Akianonymus**
Handle almost all of the pipestatus properly

Fix -i/ --save-info flag when -d flag is used

Add fallback config path when gupload is not installed system wide

### CODE REVIEW

File: sync.sh [hunk 1]
```diff
@@ -284,8 +288,9 @@ _start_new_loop() {
         printf "%b\n" "Job started.\nLocal Folder: ${INPUT}\nDrive Folder: ${GDRIVE_FOLDER}"
         printf "%s\n" "PID: ${PID}"
         printf "%b\n" "PID: ${PID}|:_//_:|${FOLDER}|:_//_:|${GDRIVE_FOLDER}" >> "${SYNC_LIST}"
-        { [[ -n ${SHOW_LOGS} ]] && tail -f "${LOGS}"; } || :
+        [[ -n ${SHOW_LOGS} ]] && tail -f "${LOGS}"
     fi
+    return 0HOME
```
Comment (labbots) [inline sync.sh:293]: Codacy found an issue: [Can only return 0-255. Other data should be written to stdout.](https://app.codacy.com/manual/labbots/google-drive-upload/pullRequest?prid=5787594)

**Comment by labbots** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/labbots/google-drive-upload/pullRequest?prid=5787594&bid=18946344)
